on:
  push:
    branches:
      - main

name: "ShellCheck - basics"
permissions: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    with:
      severity: error
      ignore_names: >-
        example-simple.sh
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
